### ISSUE TITLE
Why would you make this?

### ISSUE THREAD

**Issue by lalalune** [jasondrawdy/flux-capacitor#1]
Genuinely curious

**Comment by jasondrawdy** [comment]
Mostly because I'm not very active on the platform and wondered what a commit history (for myself) would look like to be solid green. Not only that, but I wanted to look at making automated commits work too. So, in short, I got bored.

Also, more of a lesser note, sometimes companies like to check out GitHub profiles without seeing the actual commits and so it gives the illusion of working hard even though it's just an automated script.

Hope this helps!
